version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    environment:
      - RABBIT_URI=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: on-failure