apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eureka
  template:
    metadata:
      labels:
        component: eureka
    spec:
      containers:
        - name: eureka
          image: eureka-server:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-cluster-ip
spec:
  type: LoadBalancer
  selector:
    component: eureka
  ports:
    - port: 8761
      targetPort: 8761
