apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zipkin
  template:
    metadata:
      labels:
        component: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:2.23.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
          env:
            - name: RABBIT_URI
              value: amqp://rabbitmq-cluster-ip

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-cluster-ip
spec:
  type: LoadBalancer
  selector:
    component: zipkin
  ports:
    - port: 9411
      targetPort: 9411
