version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    ports:
      - 5672:5672
      - 15672:15672
  zipkin:
    image: openzipkin/zipkin:2.10.2
    ports:
      - 9411:9411
    environment:
      - RABBIT_URI=amqp://rabbitmq
    depends_on:
      - rabbitmq