version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - 5672:5672
      - 15672:15672
  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - 9411:9411
    environment:
      - RABBIT_URI=amqp://rabbitmq
    depends_on:
      - rabbitmq
  config-client:
    image: config-client:0.0.1-SNAPSHOT
    ports:
      - 8700:8700
    depends_on:
      - config-server
  config-server:
    image: config-server:0.0.1-SNAPSHOT
    ports:
      - 8888:8888
  gateway:
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit
  naming-server:
    image: naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  resilient:
    image: resilient:0.0.1-SNAPSHOT
    ports:
      - 8600:8600
  service-one:
    image: service-one:0.0.1-SNAPSHOT
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit
  service-two:
    image: service-two:0.0.1-SNAPSHOT
    ports:
      - 8200:8200
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit