version: '3.7'
services:
  gateway:
    image: gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit
  service-two:
    image: serivce-two:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit
  service-one:
    image: service-one:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit
  naming-server:
    image: naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - 8761:8761
  zipkin:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - 9411:9411
    environment:
      - RABBIT_URI=amqp://rabbitmq
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.5.3-management
    mem_limit: 300m
    ports:
      - 5672:5672
      - 15672:15672