version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    environment:
      - RABBIT_URI=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: on-failure
  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  gateway:
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - 8000:8000
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit
  service-one:
    image: service-one:0.0.1-SNAPSHOT
    ports:
      - 8100:8100
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit
  service-two:
    image: service-two:0.0.1-SNAPSHOT
    ports:
      - 8200:8200
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - spring.zipkin.baseUrl=http://zipkin:9411/
      - RABBIT_URI=amqp://rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.sender.type=rabbit